[project]
name = "agentic-test-repo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andres Morales Esquivel", email = "andresmor@microsoft.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
agentic-test-repo = "agentic_test_repo:main"

[build-system]
requires = ["uv_build>=0.8.21,<0.9.0"]
build-backend = "uv_build"
